name: CI/CD debug

on:
  push:
    branches: [master]
    paths:
      - "debug_deps/**"
  pull_request:
    branches: [master]
    paths:
      - "debug_deps/**"
  workflow_dispatch:

env:
  ELIXIR_VERSION: 1.13
  OTP_VERSION: 24.0

jobs:
  build-test:
    name: Build and Check debug_action
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: Secret123
          POSTGRES_USER: louis
          POSTGRES_DB: debug_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: debug CI
        env:
          DB_PASSWORD: Secret123
          DB_USER: louis
          DB_NAME: debug_test
        uses: ./.github/workflows/ci
        with:
          project: "debug_deps"
          elixir_version: 1.13
          otp_version: 24.0
          test_cmd: "elixir -v"
